# Generated by Django 5.2.5 on 2025-08-28 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('tender_published', 'Tender Published'), ('tender_amendment', 'Tender Amendment'), ('bid_submitted', 'Bid Submitted'), ('evaluation_result', 'Evaluation Result'), ('contract_awarded', 'Contract Awarded'), ('system', 'System'), ('reminder', 'Reminder')], max_length=20)),
                ('related_id', models.UUIDField(blank=True, null=True)),
                ('related_type', models.CharField(blank=True, max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('message_type', models.CharField(choices=[('maintenance', 'Maintenance'), ('announcement', 'Announcement'), ('alert', 'Alert'), ('update', 'Update')], max_length=15)),
                ('target_audience', models.CharField(choices=[('all', 'All Users'), ('suppliers', 'Suppliers'), ('procuring_entities', 'Procuring Entities'), ('admins', 'Administrators')], default='all', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2025, 8, 28, 7, 48, 24, 738067, tzinfo=datetime.timezone.utc))),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
