# Generated by Django 5.2.5 on 2025-09-02 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemmessage',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 2, 14, 20, 26, 378539, tzinfo=datetime.timezone.utc)),
        ),
    ]
