# Generated by Django 5.2.5 on 2025-09-16 12:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_systemmessage_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemmessage',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
