# Generated by Django 5.2.5 on 2025-08-28 07:48

import datetime
import django.db.models.deletion
import tenders.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('procurement_method', models.CharField(choices=[('open_domestic', 'Open Domestic'), ('open_international', 'Open International'), ('restricted', 'Restricted'), ('single_source', 'Single Source'), ('request_quotations', 'Request for Quotations')], max_length=20)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(default='ZMW', max_length=3)),
                ('publication_date', models.DateTimeField(default=datetime.datetime(2025, 8, 28, 7, 48, 24, 732678, tzinfo=datetime.timezone.utc))),
                ('closing_date', models.DateTimeField()),
                ('opening_date', models.DateTimeField(blank=True, null=True)),
                ('bid_validity_period', models.PositiveIntegerField(default=90, help_text='Days')),
                ('minimum_requirements', models.TextField(blank=True)),
                ('technical_specifications', models.TextField(blank=True)),
                ('evaluation_criteria', models.TextField(blank=True)),
                ('terms_conditions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('awarded', 'Awarded'), ('completed', 'Completed')], default='draft', max_length=15)),
                ('tender_stage', models.CharField(choices=[('preparation', 'Preparation'), ('published', 'Published'), ('clarification', 'Clarification'), ('submission', 'Submission'), ('evaluation', 'Evaluation'), ('award', 'Award'), ('contract', 'Contract')], default='preparation', max_length=15)),
                ('tender_security_required', models.BooleanField(default=False)),
                ('tender_security_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tender_security_type', models.CharField(blank=True, choices=[('bank_guarantee', 'Bank Guarantee'), ('insurance_guarantee', 'Insurance Guarantee'), ('cash', 'Cash')], max_length=20, null=True)),
                ('mandatory_documents', models.TextField(blank=True)),
                ('optional_documents', models.TextField(blank=True)),
                ('allow_variant_bids', models.BooleanField(default=False)),
                ('allow_electronic_submission', models.BooleanField(default=True)),
                ('auto_extend_on_amendment', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenderAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amendment_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('changes_made', models.TextField(blank=True)),
                ('closing_date_extended', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-amendment_number'],
            },
        ),
        migrations.CreateModel(
            name='TenderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('bidding_document', 'Bidding Document'), ('technical_specification', 'Technical Specification'), ('terms_conditions', 'Terms & Conditions'), ('amendment', 'Amendment'), ('clarification', 'Clarification'), ('other', 'Other')], max_length=25)),
                ('file', models.FileField(upload_to=tenders.models.tender_document_path)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('level', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='tenders.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='SupplierCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('certification_details', models.TextField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='tenders.category')),
            ],
        ),
    ]
