# Generated by Django 5.2.5 on 2025-08-28 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenders', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suppliercategory',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_supplier_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tender',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tenders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tender',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenders', to='tenders.category'),
        ),
        migrations.AddField(
            model_name='tender',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tenders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tender',
            name='procuring_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to='users.procuringentity'),
        ),
        migrations.AddField(
            model_name='tender',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tender_subcategories', to='tenders.category'),
        ),
        migrations.AddField(
            model_name='tenderamendment',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenderamendment',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='tenders.tender'),
        ),
        migrations.AddField(
            model_name='tenderdocument',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenders.tender'),
        ),
        migrations.AddField(
            model_name='tenderdocument',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='suppliercategory',
            unique_together={('user', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='tenderamendment',
            unique_together={('tender', 'amendment_number')},
        ),
    ]
