# Generated by Django 5.2.5 on 2025-09-02 14:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='mandatory_documents',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='optional_documents',
        ),
        migrations.AlterField(
            model_name='tender',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 2, 14, 20, 26, 369217, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='TenderUploadDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file_type', models.CharField(max_length=200)),
                ('max_file_size', models.PositiveIntegerField(help_text='Max file size in bytes')),
                ('mandatory', models.BooleanField(default=False)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_documents', to='tenders.tender')),
            ],
        ),
    ]
