# Generated by Django 5.2.5 on 2025-08-28 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bids', '0001_initial'),
        ('tenders', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='tenders.tender'),
        ),
        migrations.AddField(
            model_name='biddocument',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bids.bid'),
        ),
        migrations.AddField(
            model_name='bidevaluation',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='bids.bid'),
        ),
        migrations.AddField(
            model_name='bidevaluation',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bid_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='biditem',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bids.bid'),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='procuring_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='users.procuringentity'),
        ),
        migrations.AddField(
            model_name='contract',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='tender',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='tenders.tender'),
        ),
        migrations.AddField(
            model_name='contract',
            name='winning_bid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='bids.bid'),
        ),
        migrations.AddField(
            model_name='contractmilestone',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='bids.contract'),
        ),
        migrations.AddField(
            model_name='evaluationcommittee',
            name='chairperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chaired_committees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluationcommittee',
            name='secretary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary_committees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluationcommittee',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_committees', to='tenders.tender'),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='bids.evaluationcommittee'),
        ),
        migrations.AddField(
            model_name='bidevaluation',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='bids.evaluationcommittee'),
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('tender', 'supplier')},
        ),
        migrations.AlterUniqueTogether(
            name='committeemember',
            unique_together={('committee', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='bidevaluation',
            unique_together={('bid', 'evaluator')},
        ),
    ]
