# Generated by Django 5.2.5 on 2025-09-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_evaluationcriterion_tenderevaluationconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddocument',
            name='document_type',
            field=models.CharField(max_length=200),
        ),
    ]
