# Generated by Django 5.2.5 on 2025-09-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_supplierprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
