# Generated by Django 5.2.5 on 2025-09-22 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_supplierprofile_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileEditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('user', 'User'), ('supplier_profile', 'SupplierProfile'), ('entity_user', 'EntityUser')], max_length=30)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('proposed_changes', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_profile_edits', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_edit_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
